version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'malaika'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'Lyna2009Karim'
      MYSQL_ROOT_PASSWORD: 'Lyna2009Karim198322@'
    ports:
      - '3306:3306'
    expose:
      - '3306'
